### ISSUE TITLE
 ReliableTopicTest.testMessageFieldSetCorrectly occasionally crashes on github actions. [API-1809]

### ISSUE THREAD

**Issue by OzanCansel** [hazelcast/hazelcast-cpp-client#1071]
C++ compiler version: msvc-14.2
Hazelcast Cpp client version: 5.0.0
Hazelcast server version: 5.1.3
Number of the clients: -
Cluster size, i.e. the number of Hazelcast cluster members: -
OS version (Windows/Linux/OSX): Windows

Please attach relevant logs and files for client and server side.

#### Expected behaviour
Pass test

#### Actual behaviour
Crashes on test

#### Steps to reproduce the behaviour
It might be a different test but this is what I suspected.
Here is the [link](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/3784657210/jobs/6434122371).
[ReliableTopicTest_testMessageFieldSetCorrectly.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/10313081/ReliableTopicTest_testMessageFieldSetCorrectly.txt)

**Comment by srknzl** [comment]
This failed again on [Test CPP client v5.1.0 with enterprise server](https://github.com/hazelcast/client-compatibility-suites/actions/runs/6535724054/job/17771144765#logs) in the client compat. tests of 5.3.3 HZ release. https://github.com/hazelcast/client-compatibility-suites/actions/runs/6535724054/job/17771144765#logs


```
[ RUN      ] ReliableTopicTest.testMessageFieldSetCorrectly
08:42:58,116  INFO [Main] - Ping ... Pong ...
Oct 17, 2023 8:42:58 AM com.hazelcast.internal.server.tcp.TcpServerConnection
WARNING: [localhost]:5701 [dev] [5.3.3-SNAPSHOT] Connection[id=1, /127.0.0.1:5701->/127.0.0.1:35360, qualifier=null, endpoint=[127.0.0.1]:35360, remoteUuid=943d04dc-d7d5-4720-a84f-882823ece7cf, alive=false, connectionType=CPP, planeIndex=-1] closed. Reason: Exception in Connection[id=1, /127.0.0.1:5701->/127.0.0.1:35360, qualifier=null, endpoint=[127.0.0.1]:35360, remoteUuid=943d04dc-d7d5-4720-a84f-882823ece7cf, alive=true, connectionType=CPP, planeIndex=-1], thread=hz.nifty_faraday.IO.thread-in-0
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:115)
08:42:58,156  INFO [Main] - Cleaning the R.C. Cluster Manager
08:42:58,156  INFO [Main] - Shutting down the cluster.
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)

Oct 17, 2023 8:42:58 AM com.hazelcast.client.impl.ClientEndpointManager
INFO: [localhost]:5701 [dev] [5.3.3-SNAPSHOT] Destroying ClientEndpoint{connection=Connection[id=1, /127.0.0.1:5701->/127.0.0.1:35360, qualifier=null, endpoint=[127.0.0.1]:35360, remoteUuid=943d04dc-d7d5-4720-a84f-882823ece7cf, alive=false, connectionType=CPP, planeIndex=-1], clientUuid=943d04dc-d7d5-4720-a84f-882823ece7cf, clientName=hz.client_114, authenticated=true, clientVersion=5.1.0, creationTime=1697532176068, latest clientAttributes=null, labels=[]}
Oct 17, 2023 8:42:58 AM com.hazelcast.core.LifecycleService
INFO: [localhost]:5701 [dev] [5.3.3-SNAPSHOT] [localhost]:5701 is SHUTTING_DOWN
Oct 17, 2023 8:42:58 AM com.hazelcast.internal.partition.impl.MigrationManager
INFO: [localhost]:5701 [dev] [5.3.3-SNAPSHOT] Shutdown request of Member [localhost]:5701 - bfb83d8a-de3c-4421-9bfe-2026e6a52c3d this is handled
Oct 17, 2023 8:42:58 AM com.hazelcast.instance.impl.Node
INFO: [localhost]:5701 [dev] [5.3.3-SNAPSHOT] Shutting down connection manager...
Oct 17, 2023 8:42:58 AM com.hazelcast.instance.impl.Node
INFO: [localhost]:5701 [dev] [5.3.3-SNAPSHOT] Shutting down node engine...
Oct 17, 2023 8:42:58 AM com.hazelcast.instance.impl.NodeExtension
INFO: [localhost]:5701 [dev] [5.3.3-SNAPSHOT] Destroying node NodeExtension.
Oct 17, 2023 8:42:58 AM com.hazelcast.instance.impl.Node
INFO: [localhost]:5701 [dev] [5.3.3-SNAPSHOT] Hazelcast Shutdown is completed in 14 ms.
Oct 17, 2023 8:42:58 AM com.hazelcast.core.LifecycleService
08:42:58,173  INFO [Main] - TServerEventHandler.deleteContext client
INFO: [localhost]:5701 [dev] [5.3.3-SNAPSHOT] [localhost]:5701 is SHUTDOWN
./scripts/test-unix.sh: line 60: 38562 Segmentation fault      (core dumped) ${TEST_EXECUTABLE} --gtest_output="xml:CPP_Client_Test_Report.xml"
Test FAILED. Result:139
```
