### ISSUE TITLE
Test failure: ClientNearCacheTest/BasicClientReplicatedMapNearCacheTest.whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnNearCacheAdapter/0

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-cpp-client#480]
We sometimes see the test ClientNearCacheTest/BasicClientReplicatedMapNearCacheTest.whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnNearCacheAdapter/0 fail at nightly builds. The logs are:

```
/home/jenkins/jenkins/workspace/cpp-centos7-nightly-32-SHARED-Release/hazelcast/test/src/replicatedmap/nearcache/BasicClientReplicatedMapNearCacheTest.cpp:153
Value of: actual
  Actual: 1
Expected: expected
Which is: 2
Near Cache hits should be 2, but were 0 (NearCacheStatsImpl{ownedEntryCount=500, ownedEntryMemoryCost=1000, creationTime=1543356963756, hits=1, misses=1002, ratio=0.1, evictions=0, expirations=0, invalidations=2, invalidationRequests=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})

/home/jenkins/jenkins/workspace/cpp-centos7-nightly-32-SHARED-Release/hazelcast/test/src/replicatedmap/nearcache/BasicClientReplicatedMapNearCacheTest.cpp:153
Value of: actual
  Actual: 1002
Expected: expected
Which is: 1001
Near Cache misses should be 1001, but were 0 (NearCacheStatsImpl{ownedEntryCount=500, ownedEntryMemoryCost=1000, creationTime=1543356963756, hits=1, misses=1002, ratio=0.1, evictions=0, expirations=0, invalidations=2, invalidationRequests=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
```
and details:
```
01:16:03 Members [2]  {
01:16:03 	Member[localhost]:5702 - 3aea0568-b73c-46af-8d36-feab13390a9c
01:16:03 	Member[localhost]:5701 - c4ed08f2-a0af-4161-a004-b147697893ff
01:16:03 }
01:16:03 
01:16:03 27/11/2018 22:16:03.756 INFO: [0xe55fcb40] hz.client_294[dev] [3.10.2-SNAPSHOT] LifecycleService::LifecycleEvent CLIENT_CONNECTED
01:16:03 Nov 27, 2018 10:16:03 PM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
01:16:03 INFO: [localhost]:5702 [dev] [3.11] Received auth from Connection[id=15, /127.0.0.1:5702->/127.0.0.1:53610, endpoint=null, alive=true, type=CPP_CLIENT], successfully authenticated, principal: ClientPrincipal{uuid='821a43ab-9bce-4779-a79c-a9ecaf72f068', ownerUuid='c4ed08f2-a0af-4161-a004-b147697893ff'}, owner connection: false, client version: 3.10.2-SNAPSHOT
01:16:03 27/11/2018 22:16:03.757 INFO: [0xe65feb40] hz.client_294[dev] [3.10.2-SNAPSHOT] Authenticated with server Address[localhost:5702], server version:3.11 Local address: Address[127.0.0.1:53610]
01:16:04 /home/jenkins/jenkins/workspace/cpp-centos7-nightly-32-SHARED-Release/hazelcast/test/src/replicatedmap/nearcache/BasicClientReplicatedMapNearCacheTest.cpp:153: Failure
01:16:04 Value of: actual
01:16:04   Actual: 1
01:16:04 Expected: expected
01:16:04 Which is: 2
01:16:04 Near Cache hits should be 2, but were 0 (NearCacheStatsImpl{ownedEntryCount=500, ownedEntryMemoryCost=1000, creationTime=1543356963756, hits=1, misses=1002, ratio=0.1, evictions=0, expirations=0, invalidations=2, invalidationRequests=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
01:16:04 /home/jenkins/jenkins/workspace/cpp-centos7-nightly-32-SHARED-Release/hazelcast/test/src/replicatedmap/nearcache/BasicClientReplicatedMapNearCacheTest.cpp:153: Failure
01:16:04 Value of: actual
01:16:04   Actual: 1002
01:16:04 Expected: expected
01:16:04 Which is: 1001
01:16:04 Near Cache misses should be 1001, but were 0 (NearCacheStatsImpl{ownedEntryCount=500, ownedEntryMemoryCost=1000, creationTime=1543356963756, hits=1, misses=1002, ratio=0.1, evictions=0, expirations=0, invalidations=2, invalidationRequests=0, lastPersistenceTime=0, persistenceCount=0, lastPersistenceDuration=0, lastPersistenceWrittenBytes=0, lastPersistenceKeyCount=0, lastPersistenceFailure=''})
01:16:04 27/11/2018 22:16:03.982 INFO: [0xf69d17c0] hz.client_293[dev] [3.10.2-SNAPSHOT] LifecycleService::LifecycleEvent SHUTTING_DOWN
01:16:04 27/11/2018 22:16:03.982 INFO: [0xf69d17c0] hz.client_293[dev] [3.10.2-SNAPSHOT] Removed connection to endpoint: Address[localhost:5701], connection: ClientConnection{alive=0, connectionId=1, remoteEndpoint=Address[localhost:5701], lastReadTime=2018-11-27 22:16:03.981000, closedTime=2018-11-27 22:16:03.982000, connected server version=3.11}
01:16:04 27/11/2018 22:16:03.982 INFO: [0xf69d17c0] hz.client_293[dev] [3.10.2-SNAPSHOT] Removed connection to endpoint: Address[localhost:5702], connection: ClientConnection{alive=0, connectionId=2, remoteEndpoint=Address[localhost:5702], lastReadTime=2018-11-27 22:16:00.552000, closedTime=2018-11-27 22:16:03.982000, connected server version=3.11}
01:16:04 Nov 27, 2018 10:16:04 PM com.hazelcast.nio.tcp.TcpIpConnection
01:16:04 INFO: [localhost]:5701 [dev] [3.11] Connection[id=14, /127.0.0.1:5701->/127.0.0.1:42642, endpoint=[127.0.0.1]:42642, alive=false, type=CPP_CLIENT] closed. Reason: Connection closed by the other side
01:16:04 java.io.EOFException: Remote socket closed!
01:16:04 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:116)
01:16:04 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368)
01:16:04 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353)
01:16:04 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279)
01:16:04 	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234)
01:16:04 
01:16:04 Nov 27, 2018 10:16:04 PM com.hazelcast.client.impl.ClientEndpointManager
01:16:04 INFO: [localhost]:5701 [dev] [3.11] Destroying ClientEndpoint{connection=Connection[id=14, /127.0.0.1:5701->/127.0.0.1:42642, endpoint=[127.0.0.1]:42642, alive=false, type=CPP_CLIENT], principal='ClientPrincipal{uuid='dcd04d22-7776-4c9e-8837-b9cff06f8202', ownerUuid='c4ed08f2-a0af-4161-a004-b147697893ff'}, ownerConnection=true, authenticated=true, clientVersion=3.10.2-SNAPSHOT, creationTime=1543356960196, latest statistics=null}
01:16:04 Nov 27, 2018 10:16:04 PM com.hazelcast.nio.tcp.TcpIpConnection
01:16:04 INFO: [localhost]:5702 [dev] [3.11] Connection[id=14, /127.0.0.1:5702->/127.0.0.1:53582, endpoint=[127.0.0.1]:53582, alive=false, type=CPP_CLIENT] closed. Reason: Connection closed by the other side
01:16:04 java.io.EOFException: Remote socket closed!
01:16:04 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:116)
01:16:04 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368)
01:16:04 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353)
01:16:04 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279)
01:16:04 	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234)
01:16:04 
01:16:04 Nov 27, 2018 10:16:04 PM com.hazelcast.client.impl.ClientEndpointManager
01:16:04 INFO: [localhost]:5702 [dev] [3.11] Destroying ClientEndpoint{connection=Connection[id=14, /127.0.0.1:5702->/127.0.0.1:53582, endpoint=[127.0.0.1]:53582, alive=false, type=CPP_CLIENT], principal='ClientPrincipal{uuid='dcd04d22-7776-4c9e-8837-b9cff06f8202', ownerUuid='c4ed08f2-a0af-4161-a004-b147697893ff'}, ownerConnection=false, authenticated=true, clientVersion=3.10.2-SNAPSHOT, creationTime=1543356960398, latest statistics=null}
01:16:05 27/11/2018 22:16:05.584 INFO: [0xf69d17c0] hz.client_293[dev] [3.10.2-SNAPSHOT] LifecycleService::LifecycleEvent SHUTDOWN
01:16:05 27/11/2018 22:16:05.585 INFO: [0xf69d17c0] hz.client_294[dev] [3.10.2-SNAPSHOT] LifecycleService::LifecycleEvent SHUTTING_DOWN
01:16:05 27/11/2018 22:16:05.585 INFO: [0xf69d17c0] hz.client_294[dev] [3.10.2-SNAPSHOT] Removed connection to endpoint: Address[localhost:5701], connection: ClientConnection{alive=0, connectionId=1, remoteEndpoint=Address[localhost:5701], lastReadTime=2018-11-27 22:16:03.981000, closedTime=2018-11-27 22:16:05.585000, connected server version=3.11}
01:16:05 27/11/2018 22:16:05.585 INFO: [0xf69d17c0] hz.client_294[dev] [3.10.2-SNAPSHOT] Removed connection to endpoint: Address[localhost:5702], connection: ClientConnection{alive=0, connectionId=2, remoteEndpoint=Address[localhost:5702], lastReadTime=2018-11-27 22:16:03.978000, closedTime=2018-11-27 22:16:05.585000, connected server version=3.11}
01:16:05 Nov 27, 2018 10:16:05 PM com.hazelcast.nio.tcp.TcpIpConnection
01:16:05 INFO: [localhost]:5701 [dev] [3.11] Connection[id=15, /127.0.0.1:5701->/127.0.0.1:42674, endpoint=[127.0.0.1]:42674, alive=false, type=CPP_CLIENT] closed. Reason: Connection closed by the other side
01:16:05 java.io.EOFException: Remote socket closed!
01:16:05 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:116)
01:16:05 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368)
01:16:05 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353)
01:16:05 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279)
01:16:05 	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234)
01:16:05 
01:16:05 Nov 27, 2018 10:16:05 PM com.hazelcast.client.impl.ClientEndpointManager
01:16:05 INFO: [localhost]:5701 [dev] [3.11] Destroying ClientEndpoint{connection=Connection[id=15, /127.0.0.1:5701->/127.0.0.1:42674, endpoint=[127.0.0.1]:42674, alive=false, type=CPP_CLIENT], principal='ClientPrincipal{uuid='821a43ab-9bce-4779-a79c-a9ecaf72f068', ownerUuid='c4ed08f2-a0af-4161-a004-b147697893ff'}, ownerConnection=true, authenticated=true, clientVersion=3.10.2-SNAPSHOT, creationTime=1543356963555, latest statistics=null}
01:16:05 Nov 27, 2018 10:16:05 PM com.hazelcast.nio.tcp.TcpIpConnection
01:16:05 INFO: [localhost]:5702 [dev] [3.11] Connection[id=15, /127.0.0.1:5702->/127.0.0.1:53610, endpoint=[127.0.0.1]:53610, alive=false, type=CPP_CLIENT] closed. Reason: Connection closed by the other side
01:16:05 java.io.EOFException: Remote socket closed!
01:16:05 	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:116)
01:16:05 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368)
01:16:05 	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353)
01:16:05 	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279)
01:16:05 	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234)
01:16:05 
01:16:05 Nov 27, 2018 10:16:05 PM com.hazelcast.client.impl.ClientEndpointManager
01:16:05 INFO: [localhost]:5702 [dev] [3.11] Destroying ClientEndpoint{connection=Connection[id=15, /127.0.0.1:5702->/127.0.0.1:53610, endpoint=[127.0.0.1]:53610, alive=false, type=CPP_CLIENT], principal='ClientPrincipal{uuid='821a43ab-9bce-4779-a79c-a9ecaf72f068', ownerUuid='c4ed08f2-a0af-4161-a004-b147697893ff'}, ownerConnection=false, authenticated=true, clientVersion=3.10.2-SNAPSHOT, creationTime=1543356963757, latest statistics=null}
01:16:07 27/11/2018 22:16:07.188 INFO: [0xf69d17c0] hz.client_294[dev] [3.10.2-SNAPSHOT] LifecycleService::LifecycleEvent SHUTDOWN
01:16:07 [0;31m[  FAILED  ] [mClientNearCacheTest/BasicClientReplicatedMapNearCacheTest.whenCacheIsFull_thenPutOnSameKeyShouldUpdateValue_withUpdateOnNearCacheAdapter/0, where GetParam() = 0 (6994 ms)
```

**Comment by ihsandemir** [comment]
Closing after PR https://github.com/hazelcast/hazelcast-cpp-client/pull/482  Will reopen if the test fails again.
